### ISSUE TITLE
Logs are not properly formatted when using `%s`

### ISSUE THREAD

**Issue by odimko** [wimglenn/pytest-structlog#18]
Hey there! I've tried to figure this out myself but, unfortunately, I have not managed to. So the issue is the following:
when running tests with `pytest` and using `pytest-structlog`, the tests fail because `pytest-structlog` captures unformatted logs, before arguments are substituted in the log message, e.g.:
```python
import structlog
logger = structlog.get_logger(__name__)

items_count = 2
dt = 0.02

logger.info("Processed %d CC items in total in %.2f seconds", items_count, dt)
```

in my test I have
```python
assert log.has("Processed 2 CC items in total in 0.02 seconds", level="info")
```

but it fails and I can see in the printed `Captured structlog call` section:
`{'positional_args': (2, 0.02), 'event': 'Processed %d CC items in total in %.2f seconds', 'level': 'info'}`

N.B. I am using the `structlog.stdlib.PositionalArgumentsFormatter()` `structlog` processor to handle the `%s` formatting.

N.B.B. this only happens with `log.has()`; `log.events[...` works properly and all values are replaced.

**Comment by wimglenn** [comment]
@odimko  Can you show the part of the code where you call structlog.configure ?

**Comment by odimko** [comment]
```python
def setup_logging():
    """Setup the logging configuration."""
    logging.basicConfig(
        format="%(message)s",
        stream=sys.stdout,
        level=logging.INFO,
    )

    if DEFAULT_LOG_PROCESSOR == "json":

        def process_exceptions(_, __, event_dict):
            exc_from_logger = event_dict.get("exception")
            if exc_from_logger:
                print(exc_from_logger)  # noqa: T001
                capture_exception()
            return event_dict

        def copy_log_message(_, __, event_dict):
            event_from_logger = event_dict.get("event")
            if event_from_logger and not event_dict.get("message"):
                event_dict["message"] = event_from_logger
            return event_dict

        def add_app_context(_, __, event_dict):
            f, name = structlog._frames._find_first_app_frame_and_name(
                ["logging", __name__]
            )
            event_dict["origin"] = {
                "function": f.f_code.co_name,
                "file": {"name": f.f_code.co_filename, "line": f.f_lineno},
            }
            return event_dict

        structlog.configure(
            processors=[
                structlog.threadlocal.merge_threadlocal,
                structlog.stdlib.filter_by_level,
                structlog.stdlib.add_logger_name,  # module name
                structlog.stdlib.add_log_level,  # log level
                structlog.processors.format_exc_info,
                process_exceptions,
                copy_log_message,
                add_app_context,
                structlog.stdlib.PositionalArgumentsFormatter(),
                structlog.processors.TimeStamper(fmt="iso"),
                structlog.processors.StackInfoRenderer(),
                structlog.processors.JSONRenderer(),
            ],
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
        )
    else:
        structlog.configure(
            processors=[
                structlog.stdlib.filter_by_level,
                structlog.stdlib.add_logger_name,
                structlog.stdlib.add_log_level,
                structlog.stdlib.PositionalArgumentsFormatter(),
                structlog.processors.TimeStamper(fmt="iso"),
                structlog.processors.StackInfoRenderer(),
                structlog.processors.format_exc_info,
                structlog.dev.ConsoleRenderer(),
            ],
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            context_class=structlog.threadlocal.wrap_dict(dict),
        )
```

the `else` clause if executed when running locally - and this is the case in the situation described above.

**Comment by wimglenn** [comment]
Interesting.  Could you try adding this in conftest.py file?

```
import pytest
import structlog

configure = structlog.configure

@pytest.fixture(autouse=True)
def positional(log):
    configure(
        processors=[
            structlog.stdlib.PositionalArgumentsFormatter(),
            log.process,
        ],
        wrapper_class=structlog.stdlib.BoundLogger,
    )
```

**Comment by wimglenn** [comment]
@odimko  I believe this is fixed in v0.5 (just published to PyPI), let me know.

**Comment by odimko** [comment]
hi @wimglenn! I am sorry for such a delayed answer and thanks a lot for being super responsive here :) 
so I've done the following: 
- I've upgraded to 0.5 and ran the tests and they worked fine except one thing: every 3rd or 4th run the test would fail with due to the issue above (not substituted values).
- so I've added your suggested snippet above to my `conftest.py` and it works flawlessly now. 

It feels like in the first case the package does not have enough time to read the configuration to smth. any ideas?

**Comment by wimglenn** [comment]
@odimko  So, it all depends on when structlog has been configured (which you'll want to control in your test).  Extra positional arguments don't work at all in the structlog default configuration, e.g. if you run a script like this

```
import structlog
logger = structlog.get_logger()
logger.info("hello %s", "world")
```

you'll get an error on the `logger.info` line like `TypeError: meth() takes 2 positional arguments but 3 were given`. I guess the most common usage of structlog is key-value logging, so it would normally be written like `logger.info("hello", who="world")` in an app which was using structured logging.

This plugin pytest-structlog is sort of in a tricky place here, because it has no way to easily know whether it needs to use a positional arguments formatter or not. In v0.5 I try to guess, that if there was a positional argument formatter in the configured processors then we probably want to keep one in there, but this only works in the case where the logging has already been configured by the time the plugin's fixture gets injected. Which is not always the case (e.g. the user mocked out the logging configuration call, or they are just unit-testing a code path where logging never gets configured in the first place).

So, v0.5 can help in some cases but not all. Unfortunately the only way to get this working reliably may be for the user to explicitly configure a positional argument formatter in their `conftest.py` if and when they know it is needed by the library code under test (as demonstrated in the previous message).  Does that make sense?

**Comment by odimko** [comment]
@wimglenn absolutely! and thank you so much for such a thorough explanation. that does make perfect sense.
