### ISSUE TITLE
There is no way currently to filter bu `logger_name`

### ISSUE THREAD

**Issue by sshishov** [wimglenn/pytest-structlog#22]
Usually it is okay to just assert that some message in the logs with appropriate level. But it would be great to support the logger name and other metadata there.

```python
assert log.has('my_message', level='error', logger_name='my_logger')
```

Also it would be great to have a pretty-print for the library to print the diff of dictionaries (as many people are using `pytest-icdiff` or `pytest-clarity` which will represent them great dict diff in case of something differs

**Comment by wimglenn** [comment]
@sshishov  Assertions such as :

    assert log.has('my_message', level='error', logger_name='my_logger')

Should already be working fine (and [here is the test](https://github.com/wimglenn/pytest-structlog/blob/feb680c166c9439cc99f387263e2d5c83e237960/tests/test_log.py#L46-L48) for it). Are you seeing otherwise? Could you make a reproducible example?

**Comment by wimglenn** [comment]
If you want the logger name in the context dict, you'll have to add it explicitly because pytest-structlog will not do that by default.

Something like this ought to work:

```
@pytest.fixture(autouse=True)
def inject_logger_name(log):
    original_processors = structlog.get_config().get("processors", [])
    if structlog.stdlib.add_logger_name not in original_processors:
        processors = [structlog.stdlib.add_logger_name] + original_processors
        log.original_configure(processors=processors)
        yield
        log.original_configure(processors=original_processors)
```

I've considered retaining a `structlog.stdlib.add_logger_name`, similar like we do for a [positional arguments formatter](https://github.com/wimglenn/pytest-structlog/blob/cb82f00cfc47696a36797a6eeb9f65ad6e727f19/pytest_structlog.py#L120-L123), but that would be a breaking change. A better way forward (more powerful/flexible and with backwards compatibility) may be to keep the default configuration as-is, but provide some ini options for users of pytest-structlog to override the default processors for the plugin.

**Comment by sshishov** [comment]
Thanks you for the clarification, @wimglenn , your comment makes sense! And very thank you for your time!

**Comment by wimglenn** [comment]
@sshishov  FYI, in [pytest-structlog 1.0](https://pypi.org/project/pytest-structlog/1.0/) there may be an easier option available, you can run with `pytest --structlog-keep add_logger_name` or add this in your pyproject.toml configs:

```
[tool.pytest.ini_options]
structlog_keep = ["add_logger_name"]
```

If the `add_logger_name` was already present in config at the time of running tests, it will be kept in the config.
