### ISSUE TITLE
Rename fixture to capstructlog

### ISSUE THREAD

**Issue by MarkusH** [wimglenn/pytest-structlog#8]
Thank you for this neat library!

The fixture provided by pytest-structlog is named `log`. That's a very general and unspecific name. I'd like to suggest to rename it to `capstructlog` following pytest's built-in `caplog` fixture. Adding backwards compatibility shims shouldn't be an issue.

**Comment by wimglenn** [comment]
Hello @MarkusH thanks for your kind words.

I don't like `capstructlog` much. I am happy with the fixture name. If any user want to to use a different name, they can do so trivially by adding an alias in their `conftest.py` file:

```
# in conftest.py
import pytest_structlog
pytest_structlog.capstructlog = pytest_structlog.log
```

Then user can use `capstructlog` as the fixture name everywhere in tests for their project. Since everybody might have their own opinion about the best name, and since it's trivial to rename by user, I'm going to close this issue.  Cheers
